// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLHaD5tSADQPjHGy-tdIo5lcsF5f-E0G0',
    appId: '1:995196325695:web:b68203984340c66f354d8a',
    messagingSenderId: '995196325695',
    projectId: 'realestate-managementdb',
    authDomain: 'realestate-managementdb.firebaseapp.com',
    storageBucket: 'realestate-managementdb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyri2KE7eJ7IIA6FE1PVLesnj_MS3lPFg',
    appId: '1:995196325695:android:e083b09e99b253fb354d8a',
    messagingSenderId: '995196325695',
    projectId: 'realestate-managementdb',
    storageBucket: 'realestate-managementdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzjfem4M93OofEwpY7LrzxyEtTCoB7Ois',
    appId: '1:995196325695:ios:f7f0f7e8e9830471354d8a',
    messagingSenderId: '995196325695',
    projectId: 'realestate-managementdb',
    storageBucket: 'realestate-managementdb.appspot.com',
    iosClientId: '995196325695-5e4nfm6l6qpimm6buco1rc2qiegng4qe.apps.googleusercontent.com',
    iosBundleId: 'com.example.realEstateManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzjfem4M93OofEwpY7LrzxyEtTCoB7Ois',
    appId: '1:995196325695:ios:f7f0f7e8e9830471354d8a',
    messagingSenderId: '995196325695',
    projectId: 'realestate-managementdb',
    storageBucket: 'realestate-managementdb.appspot.com',
    iosClientId: '995196325695-5e4nfm6l6qpimm6buco1rc2qiegng4qe.apps.googleusercontent.com',
    iosBundleId: 'com.example.realEstateManagementSystem',
  );
}
